### ISSUE TITLE
Use UMD Modules

### ISSUE THREAD

**Issue by ScottPeterJohnson** [markaren/three-kt-wrapper#10]
Currently the wrapper generates a "plain" JS module library, which doesn't play well with webpack. The kotlin standard lib and kotlinx-html both use UMD, which might be a safer choice. 
Really this just requires adding
`compileKotlin2Js {
    kotlinOptions.moduleKind = "umd"
}`
to build.gradle. I could make a pull request if desired.

**Comment by markaren** [comment]
I'm only a hobby JS user, so I have no experience with JS package managers.
After adding this, do I have to make changes to how I load JS in i.e. https://github.com/markaren/three.kt/blob/master/example/web/hello_world.html ?

**Comment by ScottPeterJohnson** [comment]
You shouldn't have to. In a non-module environment, it should fall back to plain.

**Comment by markaren** [comment]
Then I'm happy to accept your PR. Target the dev branch

**Comment by markaren** [comment]
Applied through pull request #11 
Included in release ALPHA-5
